#!/bin/bash
#
# PreToolUse Hook: Validate Edit paths for RLCR loop and PR loop
#
# Blocks Claude from editing:
# - Todos files (should use native Task tools instead)
# - Prompt files (read-only, generated by Codex)
# - State files (managed by hooks, not Claude)
# - Goal tracker after Round 0
# - PR loop state files (.humanize/pr-loop/)
# - PR loop read-only files (pr-comment, prompt, codex-prompt, pr-check, pr-feedback)
#

set -euo pipefail

# Load shared functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
source "$SCRIPT_DIR/lib/loop-common.sh"

# ========================================
# Parse Hook Input
# ========================================

HOOK_INPUT=$(cat)
TOOL_NAME=$(echo "$HOOK_INPUT" | jq -r '.tool_name // ""')

if [[ "$TOOL_NAME" != "Edit" ]]; then
    exit 0
fi

FILE_PATH=$(echo "$HOOK_INPUT" | jq -r '.tool_input.file_path // ""')
FILE_PATH_LOWER=$(to_lower "$FILE_PATH")

# Extract session_id from hook input for session-aware loop filtering
HOOK_SESSION_ID=$(extract_session_id "$HOOK_INPUT")

# ========================================
# Block Todos and Prompt Files
# ========================================

if is_round_file_type "$FILE_PATH_LOWER" "todos"; then
    PROJECT_ROOT="${CLAUDE_PROJECT_DIR:-$(pwd)}"
    LOOP_BASE_DIR="$PROJECT_ROOT/.humanize/rlcr"
    LOOP_DIR=$(find_active_loop "$LOOP_BASE_DIR" "$HOOK_SESSION_ID")
    if [[ -z "$LOOP_DIR" ]] || ! is_allowlisted_file "$FILE_PATH" "$LOOP_DIR"; then
        todos_blocked_message "Edit" >&2
        exit 2
    fi
fi

if is_round_file_type "$FILE_PATH_LOWER" "prompt"; then
    prompt_write_blocked_message >&2
    exit 2
fi

# ========================================
# PR Loop File Protection
# ========================================

IN_PR_LOOP_DIR=$(is_in_pr_loop_dir "$FILE_PATH" && echo "true" || echo "false")

if [[ "$IN_PR_LOOP_DIR" == "true" ]]; then
    # Block state.md edits in PR loop
    if is_state_file_path "$FILE_PATH_LOWER"; then
        pr_loop_state_blocked_message >&2
        exit 2
    fi

    # Block read-only PR loop files
    if is_pr_loop_readonly_file "$FILE_PATH_LOWER"; then
        pr_loop_prompt_blocked_message >&2
        exit 2
    fi

    # For round-N-pr-resolve.md (Claude's resolution summary), validate round number
    if is_pr_round_file_type "$FILE_PATH_LOWER" "pr-resolve"; then
        validate_pr_resolve_round "$FILE_PATH_LOWER" "edit" || exit $?
        exit 0
    fi
fi

# ========================================
# Check if File is in .humanize/rlcr
# ========================================

if ! is_in_humanize_loop_dir "$FILE_PATH"; then
    exit 0
fi

# ========================================
# Find Active Loop and Current Round
# ========================================

PROJECT_ROOT="${PROJECT_ROOT:-${CLAUDE_PROJECT_DIR:-$(pwd)}}"
LOOP_BASE_DIR="${LOOP_BASE_DIR:-$PROJECT_ROOT/.humanize/rlcr}"
ACTIVE_LOOP_DIR="${LOOP_DIR:-$(find_active_loop "$LOOP_BASE_DIR" "$HOOK_SESSION_ID")}"

if [[ -z "$ACTIVE_LOOP_DIR" ]]; then
    exit 0
fi

# Detect if we're in Finalize Phase (finalize-state.md exists)
STATE_FILE_TO_PARSE=$(resolve_active_state_file "$ACTIVE_LOOP_DIR")

# Parse state file using strict validation (fail closed on malformed state)
if ! parse_state_file_strict "$STATE_FILE_TO_PARSE" 2>/dev/null; then
    echo "Error: Malformed state file, blocking operation for safety" >&2
    exit 1
fi
CURRENT_ROUND="$STATE_CURRENT_ROUND"

# ========================================
# Block State File Edits (state.md and finalize-state.md)
# ========================================
# NOTE: Check finalize-state.md FIRST because is_state_file_path also matches finalize-state.md

if is_finalize_state_file_path "$FILE_PATH_LOWER"; then
    finalize_state_file_blocked_message >&2
    exit 2
fi

if is_state_file_path "$FILE_PATH_LOWER"; then
    state_file_blocked_message >&2
    exit 2
fi

# ========================================
# Block Plan Backup Edits
# ========================================

FILENAME=$(basename "$FILE_PATH")
if [[ "$FILENAME" == "plan.md" ]]; then
    if [[ "$FILE_PATH" == *"/.humanize/rlcr/"* ]]; then
        FALLBACK="Editing plan.md backup is not allowed during RLCR loop."
        REASON=$(load_and_render_safe "$TEMPLATE_DIR" "block/plan-backup-protected.md" "$FALLBACK")
        echo "$REASON" >&2
        exit 2
    fi
fi

# ========================================
# Block Goal Tracker After Round 0
# ========================================

if is_goal_tracker_path "$FILE_PATH_LOWER" && [[ "$CURRENT_ROUND" -gt 0 ]]; then
    SUMMARY_FILE="$ACTIVE_LOOP_DIR/round-${CURRENT_ROUND}-summary.md"
    goal_tracker_blocked_message "$CURRENT_ROUND" "$SUMMARY_FILE" >&2
    exit 2
fi

# ========================================
# Validate Summary File Round Number
# ========================================

if is_round_file_type "$FILE_PATH_LOWER" "summary"; then
    # Extract filename from path (portable - works in bash and zsh)
    CLAUDE_FILENAME=$(echo "$FILE_PATH" | sed -n 's|.*\.humanize/rlcr/[^/]*/\(.*\)$|\1|p')
    if [[ -z "$CLAUDE_FILENAME" ]]; then
        CLAUDE_FILENAME=$(echo "$FILE_PATH" | sed -n 's|.*\.humanize/rlcr/\(.*\)$|\1|p')
    fi

    if [[ -n "$CLAUDE_FILENAME" ]]; then
        CLAUDE_ROUND=$(extract_round_number "$CLAUDE_FILENAME")

        if [[ -n "$CLAUDE_ROUND" ]] && [[ "$CLAUDE_ROUND" != "$CURRENT_ROUND" ]] && ! is_allowlisted_file "$FILE_PATH" "$ACTIVE_LOOP_DIR"; then
            CORRECT_PATH="$ACTIVE_LOOP_DIR/round-${CURRENT_ROUND}-summary.md"
            FALLBACK="# Wrong Round Number

You tried to {{ACTION}} round-{{CLAUDE_ROUND}}-{{FILE_TYPE}}.md but current round is **{{CURRENT_ROUND}}**.

Edit: {{CORRECT_PATH}}"
            load_and_render_safe "$TEMPLATE_DIR" "block/wrong-round-number.md" "$FALLBACK" \
                "ACTION=edit" \
                "CLAUDE_ROUND=$CLAUDE_ROUND" \
                "FILE_TYPE=summary" \
                "CURRENT_ROUND=$CURRENT_ROUND" \
                "CORRECT_PATH=$CORRECT_PATH" >&2
            exit 2
        fi
    fi
fi

exit 0
